### ISSUE TITLE
Pass entries don't show up in search

### ISSUE THREAD

**Issue by niko** [jle64/gnome-pass-search-provider#25] opened 2021-01-25 14:50 UTC
This seem to be the relevant log lines:

```
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating service name='org.gnome.ControlCenter.SearchProvider' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " label="unconfined")
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating service name='org.gnome.Contacts.SearchProvider' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " label="unconfined")
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating service name='org.gnome.Nautilus' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " label="unconfined")
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating service name='org.gnome.Calculator.SearchProvider' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " label="unconfined")
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating service name='org.gnome.Calendar' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " label="unconfined")
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating via systemd: service name='org.gnome.Pass.SearchProvider' unit='org.gnome.Pass.SearchProvider.service' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " 
label="unconfined")
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating service name='org.gnome.seahorse.Application' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " label="unconfined")
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Activating service name='org.gnome.Weather.BackgroundService' requested by ':1.42' (uid=1000 pid=2386 comm="/usr/bin/gnome-shell " label="unconfined")
Jan 25 14:54:17 critter systemd[1550]: Starting Pass search provider for GNOME Shell daemon...
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.ControlCenter.SearchProvider'
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.Pass.SearchProvider'
Jan 25 14:54:17 critter systemd[1550]: Started Pass search provider for GNOME Shell daemon.
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.seahorse.Application'
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.Weather.BackgroundService'
Jan 25 14:54:17 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.Contacts.SearchProvider'
Jan 25 14:54:18 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.Calculator.SearchProvider'
Jan 25 14:54:18 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.Nautilus'
Jan 25 14:54:18 critter dbus-daemon[1569]: [session uid=1000 pid=1569] Successfully activated service 'org.gnome.Calendar'

Jan 25 14:54:18 critter systemd[1550]: Started GnuPG cryptographic agent and passphrase cache.
Jan 25 14:54:18 critter gpg-agent[9696]: gpg-agent (GnuPG) 2.2.20 starting in supervised mode.
Jan 25 14:54:18 critter gpg-agent[9696]: using fd 3 for browser socket (/run/user/1000/gnupg/S.gpg-agent.browser)
Jan 25 14:54:18 critter gpg-agent[9696]: using fd 4 for std socket (/run/user/1000/gnupg/S.gpg-agent)
Jan 25 14:54:18 critter gpg-agent[9696]: using fd 5 for ssh socket (/run/user/1000/gnupg/S.gpg-agent.ssh)
Jan 25 14:54:18 critter gpg-agent[9696]: using fd 6 for extra socket (/run/user/1000/gnupg/S.gpg-agent.extra)
Jan 25 14:54:18 critter gpg-agent[9696]: listening on: std=4 extra=6 browser=3 ssh=5
Jan 25 14:54:18 critter gnome-shell[2386]: Received error from D-Bus search provider org.gnome.seahorse.Application.desktop during GetResultMetas: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.gnome.Shell.SearchProvider2” on object at path /org/gnome/seahorse/Application
Jan 25 14:54:18 critter gnome-shell[2386]: Wrong number of result metas returned by search provider org.gnome.seahorse.Application.desktop: expected 3 but got 0
```
Is there anything else I can do for further debugging?

Installed version:

`gnome-pass-search-provider/groovy,groovy,now 0.0~20191115+da2db41-1 all [installed]`

**Comment by jle64** [comment] 2021-01-27 11:30
Hey,

Thanks for the report.

Unfortunately I don't see anything in the log that tells me about the issue. The only error seems to be related to seahorse.

Is there anything unusual about your `pass` setup, like using a different dir than `~/.password-store` to store passwords ?

**Comment by niko** [comment] 2021-02-02 16:26
No, nothing special about `pass`. Running v1.7.3, using `~/.password-store`, having no extensions installed. It works perfectly well in a terminal.

Is there any way to run a search provider in a terminal to debug it? Where does it log?

**Comment by jle64** [comment] 2021-02-03 09:52
> Is there any way to run a search provider in a terminal to debug it?

Yes, you can totally stop the service with `systemctl --user stop org.gnome.Pass.SearchProvider.service` and start it manually by calling `/usr/lib/gnome-pass-search-provider/gnome-pass-search-provider.py` (or wherever it is installed on Ubuntu, I'm not sure) from the terminal and you should see its output, if any. I don't think you're going to see anything more from here than what you see in journalctl however.

> Where does it log?

It just writes on stderr/out so usually when started with systemd it goes to the journal.

**Comment by niko** [comment] 2021-02-03 16:36
I restarted the search provider to no avail.

`/usr/lib/gnome-pass-search-provider/gnome-pass-search-provider.py`

does not output anything when the search is called.

**Comment by jle64** [comment] 2021-02-24 04:16
Thank you for reporting the issue, unfortunately since I can't reproduce it and nothing shows up in the logs that can help me remotely dug it I'm going to close the issue. Feel free to reopen if you have more information.

**Closed by jle64** 2021-02-24 04:16 UTC
