### ISSUE TITLE
Doesn't work with 3.34

### ISSUE THREAD

**Issue by nielsk** [jle64/gnome-pass-search-provider#18] opened 2019-09-15 06:06 UTC
I have installed gnome 3.34 and gnome-pass-search-provider doesn't seem to work anymore. Results are just not shown.

**Comment by ftostevin** [comment] 2019-10-08 15:02
Removing 
https://github.com/jle64/gnome-pass-search-provider/blob/f12076dc512c677542ca9fe38686444c6f485dd9/conf/org.gnome.Pass.SearchProvider.desktop#L10
makes the results appear in the search again

**Comment by jle64** [comment] 2019-10-08 18:00
@ftostevin @nielsk I've removed the "NoDisplay=true" in the .desktop. Can you confirm that this fixes the issue (I'm not on 3.34 yet so I can't test/reproduce).

**Comment by nielsk** [comment] 2019-10-08 18:17
I can do that but it will take a day or two since I am on vacation.

**Comment by ftostevin** [comment] 2019-10-09 12:32
Works for me. Of course this has the downside that the desktop file also appears in the application search, where it doesn't do anything.

**Comment by nielsk** [comment] 2019-10-09 13:56
works for me. Thanks.

**Comment by jle64** [comment] 2019-10-09 14:56
Thanks. Closing issue then.

**Closed by jle64** 2019-10-09 14:56 UTC

**Comment by francium** [comment] 2019-10-19 18:10
@jle64 I don't think the AUR package got updated, last update was 2019-06-01

**Comment by jle64** [comment] 2019-10-22 10:58
The AUR package always uses the latest git version, so it shouldn't need to be updated.
